version: "3.9"
services:
  db:
    image: postgres:13.3
    container_name: 'db'
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    image: 'app'
    container_name: 'app'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      DB_USERNAME: 'username'
      DB_PASSWORD: 'password'
      DB_HOST: 'db'
      DB_NAME: 'test_db'
      TRANSFER_TIME: 10
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 10
        window: 20s

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4:5.7
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "paw1a@yandex.ru"
#      PGADMIN_DEFAULT_PASSWORD: "123"
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#    ports:
#      - "5050:80"
#    restart: always
#    deploy:
#      resources:
#        limits:
#          cpus: '2'
#          memory: 1G
#    depends_on:
#      - db
#    networks:
#      - backend

networks:
  backend:
    driver: bridge